excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://KidsSwimU.github.io
name: Kids Swim University
description: The ultimate resource for supplementing your child(ren)'s swim lessons.
author: KidsSwimU
avatar: http://www.kids-swim.com/Images/FavIcons/Icon48B.ico
ga_domain: 
ga_tracking_id: 